#multi_tb3_home config

# Map information
resolution: 0.05
num_class: 4

#Kernel Information
ell : 0.1
sf2 : 0.2 

#Flow kernel
flow_ell: 0.4 #0.2
flow_sf2: 0.5 # 2.5 doesn't erase too much but stick to 3

# Sampling resolutions
free_resolution: 0.5 # Free space sampling resolution
ds_resolution: 0.1 # Downsampling factor

# Information about range-finder data
scan_num: 40 # How many scans to use
max_range: 6 # Sensor max range (m)
