#multi_tb3_home config

# Map information
resolution: 0.05
num_class: 4

#Kernel Information
ell : 0.2 #is sensitive to anything less than 0.2
sf2 : 0.2 #makes a huge difference if you increase it to 1 because
#blocks become over weighted
# at 0.5, it's okay but not very representative of the environment

#Flow kernel
flow_ell: 0.2
flow_sf2: 0.5

# Sampling resolutions
free_resolution: 0.2 # Free space sampling resolution
ds_resolution: 0.1 # Downsampling factor

# Information about range-finder data
scan_num: 50 # How many scans to use
max_range: 6 # Sensor max range (m)
