#multi_tb3_home config

# Map information
resolution: 0.05
num_class: 4

#Kernel Information
ell : 0.2
sf2 : 0.2 

#Flow kernel
flow_ell: 1  #0.2
flow_sf2: 10 # 2.5doesn't erase too much but stick to 3

# Sampling resolutions
free_resolution: 0.25 # Free space sampling resolution
ds_resolution: 0.1 # Downsampling factor

# Information about range-finder data
scan_num: 300  # How many scans to use
max_range: 7 # Sensor max range (m)

#Display both spatial and spatiotemporal
show_spatial: false
