#multi_tb3_home config

# Map information
resolution: 0.1
num_class: 4

#Kernel Information
ell : 0.25
#sf2 : 0.2 

#Flow kernel
flow_ell: 0.3  #0.2 Keep flow_ell at 4 times the resolution
flow_sf2: 50 # 2.5doesn't erase too much but stick to 3

# Sampling resolutions
free_resolution: 1 # Free space sampling resolution
ds_resolution: 0.1 # Downsampling factor

# Information about range-finder data
scan_num: 500  # How many scans to use
max_range: 7 # Sensor max range (m)

#Display both spatial and spatiotemporal
show_spatial: false

moving_classes: [0, 2]