# semantickitti_04 config

# Map information
resolution: 0.3
num_class: 20 #20 # Number of classes

# #Kernel length scale
ell: 0.6
# sf2: 0.2

# Sampling resolutions
free_resolution: 1 # Free space sampling resolution
ds_resolution: 0.1 # Downsampling factor

# Information about range-finder data
scan_num: 271 # How many scans to use
max_range: -1 # Sensor max range (m)

# Dataset information
input_data_prefix: velodyne/
input_label_prefix: predictions/
lidar_pose_file: poses.txt
gt_label_prefix: labels/
evaluation_result_prefix: evaluations/
query: true
visualize: true

#Dynamic class information
moving_classes: [1, 2, 3, 4, 5, 6, 7, 8]

#Flow kernel
flow_ell: 0.6  #0.2
flow_sf2: 50